### ISSUE TITLE
Cron jobs never run

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/cronjobs#1]
I have setup in plesk the cron job to run this module, however none of them get ran.  I run it in plesk and the task runs with no errors.  I run each task in my cron task manager, and each of them runs fine.
![plesk](https://user-images.githubusercontent.com/763426/32925916-1004774c-cb0a-11e7-8ac3-bdbb9d9f86ba.PNG)

![cron](https://user-images.githubusercontent.com/763426/32925988-5f7f8dfc-cb0a-11e7-9d6f-a84cb934c2a2.png)

**Comment by firstred** [comment]
I remember this problem with the original module. I think this module needs quite an overhaul before it will work again. It's recommended to leave this module for now.

**Comment by firstred** [comment]
About to upgrade this little gem. Note that you will have to configure it differently from 2.1.0 on if you are using Plesk or anything that could run cronjobs via CLI. The `Run a PHP script` option is now recommended. Depending in your hosting you'll have to launch it like
`/mysite.com/modules/cronjobs/controllers/front/cron.php` and your token in the arguments input field: `--token=yourtoken`:
![scheduletasks](https://user-images.githubusercontent.com/6775736/34081822-a0a7d1d4-e353-11e7-9bb1-35b9c1f594c2.png)

**Comment by firstred** [comment]
Yup, that's going to be it, except the leading `/`
