### ISSUE TITLE
can't update from 2.1.2 to 2.1.3 from back-end

### ISSUE THREAD

**Issue by kintaro1981** [thirtybees/cronjobs#4]
I'm on 1.0.4 manually updated with blog instructions.

I'm trying to update from 2.1.2 to 2.13 from the backend.
The system reply with a successful update but the version is still 2.1.2.

It's the same problem I have with custom methods payments from 1.2.1 to 1.2.3 ([here](https://github.com/thirtybees/custompayments/issues/2)). (stripe updated successfully)

**Comment by firstred** [comment]
Hey,
You can try removing the module folder and extract the new folder. It's as if not all files are being overwritten.

**Comment by kintaro1981** [comment]
Done, but it still asks to upgrade.

config_it.xml:

```
<?xml version="1.0" encoding="UTF-8" ?>
<module>
	<name>cronjobs</name>
	<displayName><![CDATA[Cron tasks manager]]></displayName>
	<version><![CDATA[2.1.2]]></version>
	<description><![CDATA[Manage all your automated web tasks from a single interface.]]></description>
	<author><![CDATA[thirty bees]]></author>
	<tab><![CDATA[administration]]></tab>
	<is_configurable>1</is_configurable>
	<need_instance>1</need_instance>
	<limited_countries></limited_countries>
</module>
```

**Comment by firstred** [comment]
Do you mean that the file `config_it.xml` stays the same?

**Comment by kintaro1981** [comment]
Yes, it seems so.

**Comment by kintaro1981** [comment]
any news about that?

I have the same problem these now:
My account block for your website's footer
New products block
Cron tasks manager
Custom payment methods

**Comment by kintaro1981** [comment]
uhmmmm I enabled DEBUG MODE and PURGED CACHE and all get updated.
but the cache was disabled as I'm testing that shop.

I will monitor this thing during next module updates.

**Comment by Traumflug** [comment]
Looks like this is solved.

In either case, `config_xx.xml` not being written correctly would be a bug in thirty bees core. To verify the actual version on disk, please look into file `cronjobs.php`, function *__construct()*. About here: https://github.com/thirtybees/cronjobs/blob/master/cronjobs.php#L59

If the problem persists, don't hesitate to open another bug.
